#taps 
tap "homebrew/bundle"
tap "homebrew/services"
tap "microsoft/git"

# brews
brew "bat"
brew "chrome-cli"
brew "gh"
brew "git"
brew "htop"
brew "httpie"
brew "tree"

#casks
cask "alfred"
cask "git-credential-manager-core"

# vscode - maybe go through these and remove some
vscode "aaravb.chrome-extension-developer-tools"
vscode "beauallison.brew-services"
vscode "christian-kohler.npm-intellisense"
vscode "Compilenix.vscode-zonefile"
vscode "DavidAnson.vscode-markdownlint"
vscode "donjayamanne.githistory"
vscode "DotJoshJohnson.xml"
vscode "eamodio.gitlens"
vscode "ecmel.vscode-html-css"
vscode "eriklynd.json-tools"
vscode "esbenp.prettier-vscode"
vscode "foxundermoon.shell-format"
vscode "GitHub.copilot"
vscode "GitHub.copilot-chat"
vscode "ms-azuretools.vscode-docker"
vscode "ms-python.python"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode.live-server"
vscode "mtxr.sqltools"
vscode "PKief.material-icon-theme"
vscode "shd101wyy.markdown-preview-enhanced"
vscode "VisualStudioExptTeam.intellicode-api-usage-examples"
vscode "VisualStudioExptTeam.vscodeintellicode"
vscode "xabikos.JavaScriptSnippets"
vscode "yzhang.markdown-all-in-one"
vscode "zh9528.file-size"
